### ISSUE TITLE
RSNA abstract

### ISSUE THREAD

**Issue by zietzm** [tlhpaul/CIS537_2018Fall#9]
This is issue will track ToDo lists and progress on the work for the abstract we hope to submit to [RNSA 2019](https://www.rsna.org/Annual-Meeting).

Submission deadline is [Wednesday, April 10, 2019, 12 p.m. CT.](https://www.rsna.org/annual-meeting/abstract-submission) 

@gastouna Feel free to comment here at any level of the planning/execution. Not expecting you to go through code line-by-line, but we always value any input you may want to offer.

**Comment by zietzm** [comment]
## TODO:
- [x] Update preprocessing pipeline for maximum reproducibility. Should save full data as a [compressed `.npz` file](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.savez_compressed.html).
- [x] Reformat Keras CNN as a function that takes hyperparameters as parameters and returns a trained model. This should handle averaging over a few train/test split seeds. Likely will have an API like 
```python
def train_model(size_layer_1, size_layer_2, size_layer_3, dropout_1, dropout_2, noise, 
                learning_rate, kernel_size, max_pool_size):
    ...
```
- [x] Reformat testing and performance interrogation into a function that takes a trained CNN and returns metrics like F1, AUC, sensitivity, and specificity. Something like 
```python
def evaluate(trained_model):
    # Compute AUC
    # Compute F1
    ...
```
- [x] Build function to save ROC curves when the performance was noteworthy.
```python
def eval_roc(model):
    ...
```
- [x] Setup large grid-search for hyperparameter optimization. I imagine this being basically:
```python
layer_1 = [8, 16]
layer_2 = [8, 16]
layer_3 = [0, 5]
dropout_1 = [0, 0.2]
dropout_2 = [0, 0.2]
noise = [0, 0.1]
learning_rates = [1e-5, 1e-4, 1e-3]
kernel_size = [2, 3]
max_pool_size = [2,]

best_auc = 0.5
best_f1 = 0

for parameter_settings in itertools.product(
        layer_1, layer_2, layer_3, dropout_1, dropout_2, noise, learning_rates, 
        kernel_size, max_pool_size):
    model = train_model(*parameter_settings)
    auc, f1, sensitivity, specificity = evaluate(model)

    # Save performance (append to file)
    with open('../data/grid_search_results.tsv', 'a') as res:
        res.write(f'{auc :.5f}\t{f1 :.5f}\t{sensitivity :.5f}\t{specificity :.5f}')

    # Save model if it's an improvement
    if (auc > best_auc) or (f1 > best_f1):
        best_auc = auc
        best_f1 = f1
        string_params = '_'.join(parameter_settings)
        model_path = pathlib.Path(f'../model/{string_params}/')
        model_path.mkdir(parents=True, exist_ok=True)
        model.save(model_path.joinpath('trained_model.h5'))

        # Save ROC curve as TPR and FPR
        fpr, tpr = eval_roc(model)
        np.savez_compressed(model_path.joinpath('roc_curve.npz'), fpr=fpr, tpr=tpr)
```
The grid search above results in 384 hyperparameter combinations. If each takes roughly 20 minutes to compute, this should take 5.3 days to search. I had originally looked a much larger search, but I quickly realized that a few more search parameters balloon the computation time (up to several months).

**Comment by NehalD99** [comment]
I have created a new branch and updated the CNN file for hyperparameter optimization(with stratified cross validation)
@zietzm You may take a look at it and create a new TODO accordingly
Also on GPU the several epochs of training finishes within 5 minutes. So the search might finish in a day.
I dont have access to the lab computer so you may look into this.
Let me know if further automation or more tasks are needed
I have merged evaluate and eval_roc function for now
Please verify prediction results for a simple setting if possible, though I have verified them.
I will also carry it out once again.

@gastouna updating you on our task
